title: Open Wiki of Electrochemical Methods
# description: 
theme: just-the-docs

url: https://anderfuller.github.io/owem-site

math: mathjax

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
